# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket  = "aws-terraform-state-backend-testing"
    encrypt = true
    key     = "aws_s3/terraform.tfstate"
    region  = "eu-central-1"
  }
}
